import = ["/home/njent/.config/alacritty/alacritty-theme/themes/solarized_dark.toml"]

[font]
size = 12.0

[font.bold]
family = "Monoid"

[font.bold_italic]
family = "Monoid"

[font.italic]
family = "Monoid"

[font.normal]
family = "Monoid"

[window]
startup_mode = "Windowed"
padding.x = 15
padding.y = 15

[keyboard]
bindings = [
    { key = "N", mods = "Command", action = "CreateNewWindow" },
    { key = "N", mods = "Command | Shift", action = "CreateNewTab" },
]
