# Interact with playerctl use F keys because I don't have a keyboard with media controls

set $play_pause playerctl play-pause
set $play_prev playerctl previous
set $play_next playerctl next

bindsym $mod+F8 exec $play_pause
bindsym $mod+F6 exec $play_prev
bindsym $mod+F7 exec $play_next
